import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import type { ContentBundle } from '../types'
import { buildContent } from './build'

/**
 * Renders the bundle as a typed module rather than JSON: the dts generator cannot
 * trace a `.json` import, and a plain module bundles identically for both the npm
 * build and the Worker.
 */
export const renderModule = (bundle: ContentBundle): string =>
  [
    '// Generated by `pnpm gen` from the repo sources - do not edit.',
    "import type { ContentBundle } from '../types'",
    '',
    `export const bundle: ContentBundle = ${JSON.stringify(bundle, null, 2)}`,
    '',
  ].join('\n')

/** Builds the bundle and writes it to `outputPath`. Returns what was written. */
export const emitContent = async (outputPath: string): Promise<ContentBundle> => {
  const bundle = await buildContent()
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, renderModule(bundle))
  return bundle
}
