import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadPackageFile, repoRoot } from '@soroush.tech/docs-content/node'
import { tokenPath } from '../tokenPath'
import type { ContentBundle } from '../types'

/** Where the Claude Code plugin keeps the reference files it ships. */
export const pluginReferencesDir = (): string =>
  join(
    repoRoot(),
    'plugins',
    'soroush-design-system',
    'skills',
    'soroush-design-system',
    'references'
  )

const GENERATED_NOTE =
  '<!-- Generated by `pnpm --filter @soroush.tech/mcp gen -- --plugin`. Do not edit by hand. -->'

/** The component inventory, as the skill's `references/components.md`. */
export const renderComponentsReference = (bundle: ContentBundle): string => {
  const groups = new Map<string, ContentBundle['components']>()
  for (const component of bundle.components) {
    const key = component.category ?? `${component.packageName}`
    groups.set(key, [...(groups.get(key) ?? []), component])
  }
  return [
    GENERATED_NOTE,
    '',
    '# Components',
    '',
    `The ${bundle.components.length} components shipped by the design system, and when to reach for each.`,
    'Import every component from its own subpath.',
    '',
    ...[...groups].flatMap(([label, items]) => [
      `## ${label}`,
      '',
      ...items.map((item) => `- **${item.name}** - ${item.summary}`),
      '',
    ]),
  ].join('\n')
}

/** The token contract, as the skill's `references/tokens.md`. */
export const renderTokensReference = (bundle: ContentBundle): string =>
  [
    GENERATED_NOTE,
    '',
    '# Token contract',
    '',
    `Every scale on \`theme\`, serialized from \`baseTheme\` (@soroush.tech/design-system ${bundle.version}).`,
    'Reference tokens through the theme; a literal value in a component is a bug.',
    '',
    ...bundle.tokens.flatMap((scale) => [
      `## ${scale.name}`,
      '',
      ...scale.tokens.map(
        ({ path, value }) => `- \`theme.${tokenPath(scale.name, path)}\` - ${String(value)}`
      ),
      '',
    ]),
  ].join('\n')

// Consumer references the design-system package owns; the plugin ships copies so the
// skill works without the repo checked out.
const COPIED = ['setup.md', 'layout-kit.md', 'theme.ts', 'providers.tsx']

const pluginFiles = (bundle: ContentBundle): Array<{ name: string; body: string }> => [
  { name: 'components.md', body: renderComponentsReference(bundle) },
  { name: 'tokens.md', body: renderTokensReference(bundle) },
  ...COPIED.map((name) => ({
    name,
    body: loadPackageFile('design-system', `docs/consumer/${name}`),
  })),
]

export interface PluginSyncResult {
  /** Files whose committed content differs from what the pipeline renders. */
  stale: string[]
}

/**
 * Writes (or, in check mode, compares) the plugin's reference files. They are
 * committed because users install the plugin from git, so a `--check` run in the
 * pre-commit hook is what keeps them honest.
 */
export const syncPluginReferences = (
  bundle: ContentBundle,
  check = false,
  dir = pluginReferencesDir()
): PluginSyncResult => {
  if (!check) mkdirSync(dir, { recursive: true })
  const stale: string[] = []
  for (const { name, body } of pluginFiles(bundle)) {
    const path = join(dir, name)
    let current: string | undefined
    try {
      current = readFileSync(path, 'utf8')
    } catch {
      current = undefined
    }
    if (current === body) continue
    stale.push(name)
    if (!check) writeFileSync(path, body)
  }
  return { stale }
}
